
environment:
  PYTHON_V: 3.8

  matrix:
  - job_name: windows
    image: Visual Studio 2022

version: '{build}'

skip_tags: true
clone_depth: 1

branches:
  only:
    - master
    - main

stack:
  python ${PYTHON_V}

for:
-
  matrix:
    only:
      - job_name: windows
    fast_finish: false

  environment:
    PYTHON_V: 3.8
    QT_PATH: "D:/Qt/5.15.2/msvc2019_64"  #there is no msvc2022_64 under /qt*
    PYQT: "6"
    PYUIC: "pyuic6.exe"
    BUILD_PYINSTALLER: "True"
    ARTISAN_LEGACY: "False"
    VC_REDIST: "https://aka.ms/vs/17/release/vc_redist.x64.exe"  #redistributable for VS 2015-2022
    VCVARSALL: "D:/Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build/vcvarsall.bat"

  install:
    - cmd: echo Windows Install

    - ps: |
        if (Test-Path env:PYUPGRADE_WIN_V) {
            $env:PREV_PYTHON_V = $env:PYTHON_V
            $env:PYTHON_V = ($env:PYUPGRADE_WIN_V -split '\.')[0..1] -join '.'
        }

    - ps: $env:PYTHON_PATH = "C:/Python$($env:PYTHON_V -replace '\.','')-x64"
    - ps: Write-Host $env:PYTHON_PATH

    - ps: $env:QT_TRANSL = "$env:PYTHON_PATH/Lib/site-packages/PyQt6/Qt6/translations"

    - ps: $env:PYINSTALLER_VER = Select-String -Path ./src/requirements.txt "pyinstaller==([\d\.]*).*platform_system='Windows'" -List | ForEach-Object {$_.Matches.Groups[1].Value}
    - ps: Write-Host "PYINSTALLER_VER= $env:PYINSTALLER_VER"

    - cmd: set PATH=%PYTHON_PATH%;%PYTHON_PATH%\Scripts;%PATH%

    - cmd: .ci/install-win.bat

  build_script:
    - cmd: echo Windows Build
    - cmd: cd src

    - ps: $YEAR=(Get-Date).year
    - ps: gc version-metadata.yml | %{ $_ -replace "yyyy", "$YEAR" } | out-file newfile -encoding ascii
    - ps: move -force newfile version-metadata.yml

    - ps: $GIT_VERSION=git rev-parse --verify --short HEAD
    - ps: gc artisanlib/__init__.py | %{ $_ -replace "__revision__ = '.*'", "__revision__ = '$GIT_VERSION'" } | out-file newfile -encoding ascii
    - ps: move -force newfile artisanlib/__init__.py

    - cmd: build-win3-pi.bat

  artifacts:
    - path: 'src\%artifact_prefix%-*.zip'

  deploy_script:
    - cmd: bash ../.ci/upload.sh artisan-*.zip